# this will deploy the safe secure tested code to production server through SSH.
name: Deploy to production server

on : 
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}

        steps:

            - name : checking out the code
              uses : actions/checkout@v7

            - name : doing SSH to server & creating app folder in it
              uses: appleboy/ssh-action@v1
              with:
                    host: ${{ secrets.EC2_SSH_HOST }} # Public IP address of the EC2 instance
                    username: ${{ secrets.EC2_SSH_USERNAME }} # Username of the EC2 instance
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # Private key of the EC2 instance from key pair
                    script: |
                         echo "Installing required packages & folders"
                         sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                         sudo usermod -aG docker $USER
                         mkdir -p devops
                        

            - name: Copy the docker-compose file into server folder
              uses: appleboy/scp-action@v1
              with:
                    host: ${{ secrets.EC2_SSH_HOST }}
                    username: ${{ secrets.EC2_SSH_USER }}
                    key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                    source: docker-compose.yml
                    target: ~/devops     
                    
                    
            - name: SSH to Prod server & run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: | 
                 echo "Running App"
                
                 export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                 export DOCKER_TAG=${{ github.sha }}   
                 echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ vars.DOCKERHUB_USER }} --password-stdin
                 cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always        
                # exporting username and tag for login to docker hub , | will give left side output to right side as input, so we can use it 
                # for docker login, so basically here "docker token" is treated as standard input for the --password flagdsd