# this is a devsecops pipeline which connect all the workflows
name : DevSecOps End to End Pipeline

on : 
    push:
        branches: [main]

jobs:

    # CI(Continuous Integration with security scanning)
    code-quality:
        uses : ./.github/workflows/code-quality.yml

    secrets-scan:
        
        uses : ./.github/workflows/secrets-scan.yml
     
    dependencies-scan:
        
        uses : ./.github/workflows/dependencies-scan.yml

    docker-scan:
        
        uses : ./.github/workflows/docker-lint.yml  
        


    # Build after security scanning is done    

    build :
        needs : [code-quality, secrets-scan, dependencies-scan, docker-scan]
        uses : ./.github/workflows/docker-build-push.yml
        secrets: inherit # this will inherit all the secrets from parent workflow    

    # Once image is build we will scan it for vulnerabilities using trivy   
    
    image-scan:
         
        needs : build
        uses : ./.github/workflows/image-scan.yml
        secrets: inherit


    # CD - Deploy to prod server
    
    deploy :
        needs : image-scan
        uses : ./.github/workflows/deploy_to_prodserver.yml
        secrets: inherit

        

