# credentials, api keys , sensitive data etc will be scanned in this workflow using GITLEAKS
name : secrets-scan

on : 
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checking out the code
              uses : actions/checkout@v7
              with:
                fetch-depth: 0

            - name: Run Gitleaks scanner
              uses : gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # whener github run workflow it generate this token which is given to 
                # runner . runner used it to scan the code.
         